name: iOS starter workflow

on: [push]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s '/Applications/Xcode_16_beta_3.app/Contents/Developer'
      - env:
          API_KEY_NewsAPI: ${{secrets.API_KEY_NewsAPI}}
          SCRIPT_INPUT_FILE_0: '/Users/runner/Library/Developer/Xcode/DerivedData/NewsApp-bfllpabxcebrfrflppslxpblqynk/Build/Products/Development_Debug-iphonesimulator/spp'
        run: xcodebuild test -skipPackagePluginValidation -project  NewsApp/NewsApp.xcodeproj -scheme Development -sdk iphonesimulator18.0 -destination platform='iOS Simulator,name=iPhone 15 Pro,OS=18.0'
